"""Current-frame robot-only rejection evidence for visual grounding.

The mask is already generated by the RGB-D observation's robot self-filter.
No object segmentation, scene identities, hidden positions or new sensors.
"""
from pathlib import Path
import numpy as np
from robotwin_harness_v3 import SkillError


def current_robot_mask(observation, image_shape):
    from robodawn.camera_views import camera_of,evidence_path
    index=observation.get('observation_id')
    if not isinstance(index,int):return None
    evidence=evidence_path(observation['image_paths'][0],index,camera_of(observation))
    if evidence is None or not evidence.is_file():return None
    with np.load(evidence,allow_pickle=False) as data:
        if 'robot_self_mask' not in data:return None
        mask=np.asarray(data['robot_self_mask'],bool)
    if mask.shape!=tuple(image_shape[:2]):raise SkillError('Current self-mask and image calibration disagree')
    return mask


def robot_at_point(mask, point, crop=None):
    if mask is None:return False
    height,width=mask.shape
    if crop is None:pixel=np.asarray(point)*[width-1,height-1]/1000
    else:
        low,high,_,_=crop
        pixel=np.asarray(point)*(high-low)/1000+low
    x,y=np.rint(pixel).astype(int)
    return bool(mask[int(np.clip(y,0,height-1)),int(np.clip(x,0,width-1))])


def robot_hidden_image(image,mask,crop=None):
    """Same RGB view with only calibrated self pixels made neutral grey."""
    if crop is not None:
        low,high,_,_=crop
        mask=mask[low[1]:high[1]+1,low[0]:high[0]+1]
    result=image.copy();result[mask]=[150,150,150]
    return result


def current_contact_mask(observation):
    """Executor-compatible foreground from this camera's current RGB-D."""
    from robodawn.camera_views import camera_of,evidence_path
    camera=camera_of(observation)
    if not isinstance(observation.get('observation_id'),int):return None
    path=evidence_path(observation['image_paths'][0],observation.get('observation_id'),camera)
    if path is None or not path.is_file() or 'table_height_m' not in observation:return None
    with np.load(path,allow_pickle=False) as data:
        if 'world_xyz' not in data or 'valid' not in data:return None
        cloud=data['world_xyz'];valid=data['valid'].astype(bool)
        if cloud.shape!=valid.shape+(3,):raise SkillError('Contact depth calibration shape mismatch')
        if 'robot_self_mask' in data:valid &= ~data['robot_self_mask'].astype(bool)
    table=float(observation['table_height_m'])
    mask=valid & np.isfinite(cloud).all(axis=2)
    mask &= (cloud[:,:,2]>table+.004)&(cloud[:,:,2]<table+.38)
    mask &= (np.abs(cloud[:,:,0])<.45)&(cloud[:,:,1]>-.40)&(cloud[:,:,1]<.35)
    mask[1:,:] &= ~(np.linalg.norm(np.diff(cloud,axis=0),axis=2)>.025)
    mask[:,1:] &= ~(np.linalg.norm(np.diff(cloud,axis=1),axis=2)>.025)
    return mask


def held_destination_arm(observation,action):
    if action.get('skill')!='place':return None
    if action.get('relation','on') not in ('on','inside'):return None
    from robodawn.episodic_memory import object_key
    target=object_key(action.get('target',''))
    for side,state in observation.get('sensors',{}).items():
        if (side!=action.get('arm') and state.get('holding') and state.get('remembered_object')
                and object_key(state['remembered_object'])==target):return side
    return None


def admit_wrist_contact(observation, action, include_head=False):
    """Reject unsupported source contacts before accepting a view or memory.

    This is a necessary execution precondition, not an identity classifier.
    Destination surfaces/interiors and whole-object identity queries are not
    contact points and must not inherit the above-table grasp constraint.
    """
    from robodawn.camera_views import camera_of
    camera=camera_of(action)
    if action.get('skill')=='arc':
        from robodawn.camera_views import evidence_path
        from articulation_geometry import measured_line_evidence
        path=evidence_path(observation['image_paths'][0],observation.get('observation_id'),camera)
        if path is None or not path.is_file() or 'table_height_m' not in observation:
            raise SkillError('No current calibrated depth for visible hinge grounding')
        with np.load(path,allow_pickle=False) as data:
            evidence=measured_line_evidence(data['world_xyz'],data['valid'],action.get('hinge_line'),
                                           observation['table_height_m'],data.get('robot_self_mask'))
        return dict(evidence,camera=camera,observation_id=observation['observation_id'])
    held_support=held_destination_arm(observation,action)
    from robotwin_harness_v3 import RELATIVE_DIRECTIONS
    spatial_reference=action.get('skill')=='place' and action.get('relation') in RELATIVE_DIRECTIONS
    if (camera=='head_camera' and not include_head) or (not held_support and not spatial_reference and action.get('skill') not in ('pick','grasp_handle','push','handover')):
        return None
    foreground=current_contact_mask(observation)
    if foreground is None:
        if camera=='head_camera':return None  # legacy/mock observations may omit saved RGB-D
        raise SkillError('No current calibrated wrist depth for source contact')
    height,width=foreground.shape
    x0,y0,x1,y1=np.rint(np.asarray(action['bbox'])*[width-1,height-1,width-1,height-1]/1000).astype(int)
    mask=np.zeros_like(foreground);mask[y0:y1+1,x0:x1+1]=True
    mask &= foreground
    import cv2
    _,_,stats,_=cv2.connectedComponentsWithStats(mask.astype(np.uint8),8)
    largest=int(stats[1:,cv2.CC_STAT_AREA].max()) if len(stats)>1 else 0
    if largest<4:
        raise SkillError('No above-table object in current '+camera+' visual bbox; re-ground or try another current camera')
    if held_support:
        x,y=np.rint(np.asarray(action['point'])*[width-1,height-1]/1000).astype(int)
        if action.get('support')=='table' or not foreground[y,x]:
            raise SkillError('Destination is contact-verified held by '+held_support+'; a table/background point cannot represent its current support surface')
        plane=action.get('memory_guided_search',{}).get('support_plane')
        if plane:
            from robodawn.camera_views import evidence_path
            path=evidence_path(observation['image_paths'][0],observation['observation_id'],camera)
            with np.load(path,allow_pickle=False) as data:point=data['world_xyz'][y,x]
            residual=float(abs((point-np.asarray(plane['point']))@np.asarray(plane['normal'])))
            if residual>.008:
                raise SkillError('Selected held-destination point is not on the currently observed broad supporting plane; do not place on its handle or rim')
    return dict(camera=camera,observation_id=observation['observation_id'],
                source='current_nonrobot_rgbd_contact_component',largest_component_pixels=largest)
